name: Build Matrix
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, android, linux, linux-arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'
      - run: go version
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - uses: pnpm/action-setup@v4
      - name: Install patcher dependencies for windows
        if: matrix.platform == 'windows'
        run: sudo apt-get update && bash scripts/pepare-deb.sh
      - name: Install patcher dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Pre-Patch
        run: pnpm patch-pre
      - name: Build windows x86_64
        if: matrix.platform == 'windows'
        run: pnpm build -- --windows
      - name: MSI Repack
        if: matrix.platform == 'windows'
        run: pnpm msipack
      - name: Windows artifact
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-windows-setup-patched-amd64
          path: dist/*.msi
          retention-days: 30
      - name: Build Linux x86_64
        if: matrix.platform == 'linux'
        run: pnpm build -- --linux
      - name: Build Linux arm64
        if: matrix.platform == 'linux-arm64'
        run: pnpm build -- --linux --arm64
      - name: Linux artifact Prepare
        if: matrix.platform == 'linux' || matrix.platform == 'linux-arm64'
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Linux artifact Uploading
        if: matrix.platform == 'linux' || matrix.platform == 'linux-arm64'
        run: |
          find dist -type f | while read -r file; do
            name=$(basename "$file")
            echo "Uploading $name, file: $file"
            zip - "$file" | gh-actions-artifact-client.js upload "${name}"
          done
      - name: Cache Gradle packages
        if: matrix.platform == 'android'
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Build Android
        if: matrix.platform == 'android'
        run: pnpm build-android
      - name: Android artifact
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-android-patched
          path: tailscale-android/*.apk
          retention-days: 30